// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "embape":return img`
.........7777.......
.........ffff.......
.........7777.......
....ffff777777ffff..
....ffff777777ffff..
....ffff777777ffff..
.........77777......
.........11111......
.........77777......
.........77777......
.........22722......
.........22722......
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
